// GENERATED CODE - DO NOT MODIFY BY HAND.
// Obfuscation is anti-grep only, not security.

import Foundation

private let encodedRouteValues: [String: String] = [
    "prefix": "L2FwaS9leHRlcm5hbC92MQ==",
    "usersApiPrefix": "L2FwaS92MQ==",
    "admin.cache_stats": "L2FkbWluL2NhY2hlL3N0YXRz",
    "admin.usage": "L2FkbWluL3VzYWdl",
    "admin.user_stats": "L2FkbWluL3VzZXItc3RhdHM=",
    "auth.auth_check": "L2hlYWx0aA==",
    "auth.health": "L2hlYWx0aA==",
    "auth.me": "L2F1dGgvbWU=",
    "collections.add_assets": "L2NvbGxlY3Rpb24ve2NvbGxlY3Rpb25faWR9L2Fzc2V0cy9jcmVhdGU=",
    "collections.auto_index_get": "L2NvbGxlY3Rpb24vYXV0b19pbmRleA==",
    "collections.auto_index_set": "L2NvbGxlY3Rpb24vYXV0b19pbmRleA==",
    "collections.create": "",
    "collections.delete": "L2NvbGxlY3Rpb24vZGVsZXRl",
    "collections.edit": "",
    "collections.list_groups": "L2NvbGxlY3Rpb24vZ3JvdXBz",
    "collections.update_description": "L2NvbGxlY3Rpb24vZGVzY3JpcHRpb24vdXBkYXRl",
    "collections.upload_file": "L2NvbGxlY3Rpb24vdXBsb2Fk",
    "collections.upload_folder": "L3VwbG9hZC9mb2xkZXI=",
    "collections.upload_google_drive_folder": "L2NvbGxlY3Rpb24vdXBsb2FkL2dvb2dsZV9kcml2ZQ==",
    "collections.upload_metadata_jsonl": "L2NvbGxlY3Rpb24vdXBsb2FkL21ldGFkYXRh",
    "collections.video_upload.done": "L2NvbGxlY3Rpb24vdXBsb2FkL2RvbmU=",
    "collections.video_upload.presign": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9nZXRfc2lnbmVkX3VybA==",
    "gdrive.private_auth_url": "L2dkcml2ZS9wcml2YXRlL2F1dGgtdXJs",
    "gdrive.private_download": "L2dkcml2ZS9wcml2YXRlL2ZvbGRlci9kb3dubG9hZA==",
    "images.get_image_bulk_from_urls": "L2ltYWdlL2dldF9pbWFnZV9idWxr",
    "images.get_image_from_url": "L2ltYWdlL2dldF9pbWFnZQ==",
    "images.get_url": "L2ltYWdlL2dldF91cmw=",
    "images.get_url_bulk": "L2ltYWdlL2dldF91cmxfYnVsaw==",
    "indexes.create_index": "L2luZGV4YXRpb24vam9iL2NyZWF0ZQ==",
    "indexes.delete_index": "L2luZGV4YXRpb24vaW5kZXgvZGVsZXRl",
    "indexes.embedding_models": "L2luZGV4ZXMvZW1iZWRkaW5nX21vZGVscw==",
    "indexes.index_status": "L2luZGV4YXRpb24vam9iL3tqb2JfaWR9",
    "indexes.jobs_list": "L2luZGV4YXRpb24vam9icw==",
    "metadata.internal_fallback": "L2FwaS9pbnRlcm5hbC92MS9jb2xsZWN0aW9uL3VwbG9hZC9tZXRhZGF0YQ==",
    "multipart.abort": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvYWJvcnQ=",
    "multipart.complete": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvY29tcGxldGU=",
    "multipart.create": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvY3JlYXRl",
    "multipart.sign_parts": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvc2lnbl9wYXJ0cw==",
    "multipart.status": "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvc3RhdHVz",
    "r2.credentials": "L2dldF9yMl9jcmVkZW50aWFscy8=",
    "r2.presign_upload_file": "L3VwbG9hZF9maWxlLw==",
    "r2.presign_upload_folder_video": "L3VwbG9hZF9mb2xkZXJfdmlkZW8v",
    "searches.search_video": "L3NlYXJjaA==",
    "sql.query": "L3NxbC9xdWVyeQ==",
]

func routeValue(_ key: String) -> String {
    String(decoding: Data(base64Encoded: encodedRouteValues[key]!)!, as: UTF8.self)
}

public extension Routes {
    static let specs: [RouteSpec] = [
        .init(name: "admin.cache_stats", method: "GET", path: routeValue("admin.cache_stats"), category: .usersApi, source: "users_api"),
        .init(name: "admin.usage", method: "GET", path: routeValue("admin.usage"), category: .usersApi, source: "users_api"),
        .init(name: "admin.user_stats", method: "GET", path: routeValue("admin.user_stats"), category: .active, source: "upstream"),
        .init(name: "auth.auth_check", method: "GET", path: routeValue("auth.auth_check"), category: .active, source: "upstream"),
        .init(name: "auth.health", method: "GET", path: routeValue("auth.health"), category: .active, source: "upstream"),
        .init(name: "auth.me", method: "GET", path: routeValue("auth.me"), category: .usersApi, source: "users_api"),
        .init(name: "collections.add_assets", method: "POST", path: routeValue("collections.add_assets"), category: .active, source: "upstream"),
        .init(name: "collections.auto_index_get", method: "GET", path: routeValue("collections.auto_index_get"), category: .disabled, source: "upstream"),
        .init(name: "collections.auto_index_set", method: "POST", path: routeValue("collections.auto_index_set"), category: .disabled, source: "upstream"),
        .init(name: "collections.create", method: "NONE", path: routeValue("collections.create"), category: .disabled, source: "sdk_contract"),
        .init(name: "collections.delete", method: "DELETE", path: routeValue("collections.delete"), category: .active, source: "upstream"),
        .init(name: "collections.edit", method: "NONE", path: routeValue("collections.edit"), category: .disabled, source: "sdk_contract"),
        .init(name: "collections.list_groups", method: "GET", path: routeValue("collections.list_groups"), category: .active, source: "upstream"),
        .init(name: "collections.update_description", method: "POST", path: routeValue("collections.update_description"), category: .active, source: "upstream"),
        .init(name: "collections.upload_file", method: "POST", path: routeValue("collections.upload_file"), category: .active, source: "upstream"),
        .init(name: "collections.upload_folder", method: "POST", path: routeValue("collections.upload_folder"), category: .disabled, source: "upstream"),
        .init(name: "collections.upload_google_drive_folder", method: "POST", path: routeValue("collections.upload_google_drive_folder"), category: .deprecated, source: "upstream"),
        .init(name: "collections.upload_metadata_jsonl", method: "POST", path: routeValue("collections.upload_metadata_jsonl"), category: .active, source: "upstream"),
        .init(name: "collections.video_upload.done", method: "POST", path: routeValue("collections.video_upload.done"), category: .signedSingle, source: "sdk_python"),
        .init(name: "collections.video_upload.presign", method: "POST", path: routeValue("collections.video_upload.presign"), category: .signedSingle, source: "sdk_python"),
        .init(name: "gdrive.private_auth_url", method: "POST", path: routeValue("gdrive.private_auth_url"), category: .disabled, source: "upstream"),
        .init(name: "gdrive.private_download", method: "POST", path: routeValue("gdrive.private_download"), category: .disabled, source: "upstream"),
        .init(name: "images.get_image_bulk_from_urls", method: "POST", path: routeValue("images.get_image_bulk_from_urls"), category: .image, source: "apionly_serve_img.py"),
        .init(name: "images.get_image_from_url", method: "POST", path: routeValue("images.get_image_from_url"), category: .image, source: "apionly_serve_img.py"),
        .init(name: "images.get_url", method: "POST", path: routeValue("images.get_url"), category: .image, source: "apionly_serve_img.py"),
        .init(name: "images.get_url_bulk", method: "POST", path: routeValue("images.get_url_bulk"), category: .image, source: "apionly_serve_img.py"),
        .init(name: "indexes.create_index", method: "POST", path: routeValue("indexes.create_index"), category: .active, source: "upstream"),
        .init(name: "indexes.delete_index", method: "DELETE", path: routeValue("indexes.delete_index"), category: .active, source: "upstream"),
        .init(name: "indexes.embedding_models", method: "GET", path: routeValue("indexes.embedding_models"), category: .disabled, source: "upstream"),
        .init(name: "indexes.index_status", method: "GET", path: routeValue("indexes.index_status"), category: .active, source: "upstream"),
        .init(name: "indexes.jobs_list", method: "GET", path: routeValue("indexes.jobs_list"), category: .active, source: "upstream"),
        .init(name: "metadata.internal_fallback", method: "POST", path: routeValue("metadata.internal_fallback"), category: .active, source: "sdk_python"),
        .init(name: "multipart.abort", method: "POST", path: routeValue("multipart.abort"), category: .multipartExperimental, source: "sdk_python"),
        .init(name: "multipart.complete", method: "POST", path: routeValue("multipart.complete"), category: .multipartExperimental, source: "sdk_python"),
        .init(name: "multipart.create", method: "POST", path: routeValue("multipart.create"), category: .multipartExperimental, source: "sdk_python"),
        .init(name: "multipart.sign_parts", method: "POST", path: routeValue("multipart.sign_parts"), category: .multipartExperimental, source: "sdk_python"),
        .init(name: "multipart.status", method: "GET", path: routeValue("multipart.status"), category: .multipartExperimental, source: "sdk_python"),
        .init(name: "r2.credentials", method: "GET", path: routeValue("r2.credentials"), category: .usersApi, source: "users_api"),
        .init(name: "r2.presign_upload_file", method: "GET", path: routeValue("r2.presign_upload_file"), category: .usersApi, source: "users_api"),
        .init(name: "r2.presign_upload_folder_video", method: "POST", path: routeValue("r2.presign_upload_folder_video"), category: .usersApi, source: "users_api"),
        .init(name: "searches.search_video", method: "POST", path: routeValue("searches.search_video"), category: .active, source: "upstream"),
        .init(name: "sql.query", method: "POST", path: routeValue("sql.query"), category: .disabled, source: "upstream"),
    ]
}
